// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function CaptureScreenshotNow():Promise<void>;

export function ChangePassword(arg1:string,arg2:string):Promise<void>;

export function CleanupOldScreenshots():Promise<void>;

export function DeleteScreenshot(arg1:number):Promise<void>;

export function DisableAutoStart():Promise<void>;

export function EnableAutoStart():Promise<void>;

export function GetActivityLog(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<models.ActivitySample>>;

export function GetAppStatus():Promise<models.AppStatus>;

export function GetAppVersion():Promise<string>;

export function GetDailyAppUsage(arg1:string):Promise<Array<models.DailyAppUsage>>;

export function GetDashboardData(arg1:string):Promise<models.DashboardData>;

export function GetScreenshotFileURL(arg1:string):Promise<string>;

export function GetScreenshotServerURL():Promise<string>;

export function GetScreenshots(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<Array<models.Screenshot>>;

export function GetSettings():Promise<Record<string, string>>;

export function HasPassword():Promise<boolean>;

export function HideWindow():Promise<void>;

export function IsAutoStartEnabled():Promise<boolean>;

export function IsMonitoringPaused():Promise<boolean>;

export function OpenDataFolder():Promise<void>;

export function OpenScreenshotFolder():Promise<void>;

export function PauseMonitoring():Promise<void>;

export function RebuildDailySummary(arg1:string):Promise<void>;

export function RequestExit(arg1:string):Promise<void>;

export function ResumeMonitoring():Promise<void>;

export function SelectScreenshotFolder():Promise<string>;

export function SetPassword(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function UpdateSetting(arg1:string,arg2:string):Promise<void>;

export function UpdateSettings(arg1:Record<string, string>):Promise<void>;

export function VerifyPassword(arg1:string):Promise<boolean>;
