// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreenshotNow() {
  return window['go']['main']['App']['CaptureScreenshotNow']();
}

export function ChangePassword(arg1, arg2) {
  return window['go']['main']['App']['ChangePassword'](arg1, arg2);
}

export function CleanupOldScreenshots() {
  return window['go']['main']['App']['CleanupOldScreenshots']();
}

export function DeleteScreenshot(arg1) {
  return window['go']['main']['App']['DeleteScreenshot'](arg1);
}

export function DisableAutoStart() {
  return window['go']['main']['App']['DisableAutoStart']();
}

export function EnableAutoStart() {
  return window['go']['main']['App']['EnableAutoStart']();
}

export function GetActivityLog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetActivityLog'](arg1, arg2, arg3, arg4);
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetDailyAppUsage(arg1) {
  return window['go']['main']['App']['GetDailyAppUsage'](arg1);
}

export function GetDashboardData(arg1) {
  return window['go']['main']['App']['GetDashboardData'](arg1);
}

export function GetScreenshotFileURL(arg1) {
  return window['go']['main']['App']['GetScreenshotFileURL'](arg1);
}

export function GetScreenshotServerURL() {
  return window['go']['main']['App']['GetScreenshotServerURL']();
}

export function GetScreenshots(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetScreenshots'](arg1, arg2, arg3, arg4, arg5);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasPassword() {
  return window['go']['main']['App']['HasPassword']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function IsAutoStartEnabled() {
  return window['go']['main']['App']['IsAutoStartEnabled']();
}

export function IsMonitoringPaused() {
  return window['go']['main']['App']['IsMonitoringPaused']();
}

export function OpenDataFolder() {
  return window['go']['main']['App']['OpenDataFolder']();
}

export function OpenScreenshotFolder() {
  return window['go']['main']['App']['OpenScreenshotFolder']();
}

export function PauseMonitoring() {
  return window['go']['main']['App']['PauseMonitoring']();
}

export function RebuildDailySummary(arg1) {
  return window['go']['main']['App']['RebuildDailySummary'](arg1);
}

export function RequestExit(arg1) {
  return window['go']['main']['App']['RequestExit'](arg1);
}

export function ResumeMonitoring() {
  return window['go']['main']['App']['ResumeMonitoring']();
}

export function SelectScreenshotFolder() {
  return window['go']['main']['App']['SelectScreenshotFolder']();
}

export function SetPassword(arg1) {
  return window['go']['main']['App']['SetPassword'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function UpdateSetting(arg1, arg2) {
  return window['go']['main']['App']['UpdateSetting'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function VerifyPassword(arg1) {
  return window['go']['main']['App']['VerifyPassword'](arg1);
}
